// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjpbwdyyhqgwkzuymzer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcGJ3ZHl5aHFnd2t6dXltemVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDY5ODcsImV4cCI6MjA1OTE4Mjk4N30.duRVLyRI_zJ8po3dfrrgrq9vrZJ-rrezUgTVNY_EgRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);