
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omymwkunilzdnkswedyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9teW13a3VuaWx6ZG5rc3dlZHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTM2NjUsImV4cCI6MjA2NDQ4OTY2NX0.n5wKdzVeQNpsVY7aIpbe9lJQB6nWV86FElM5T2AHOoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
